### ISSUE TITLE
Add alternative Teddit link to r/DeGoogle

### ISSUE THREAD

**Issue by mckinley360** [ElderSnake/dontbeevil-site#1]
There's a lot of good information on that forum, but in the spirit of privacy it would be good to add an alternative link to a Teddit instance so people can take a look without subjecting themselves to Reddit's tracking.
I would recommend linking to the official Teddit instance. It can be slow to respond at times, but it's the only public instance I know of that's likely to stay up for the foreseeable future. https://teddit.net/r/degoogle

**Comment by ElderSnake** [comment]
Very good point, as someone who sometimes uses Teddit that was slack of me. Will get on it, thanks!
